### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by darrendaz** [learn-co-curriculum/react-state-readme#2]
In general, would be nice and efficient if we had codepens or something to play around with these code examples instead of having to clone and open in IDE from github. Similar to how w3schools has the Try It buttons or how the react documentation has the try it on codepen button.

**Comment by maxwellbenton** [comment]
Hi @darrendaz,

Thank you for providing this feedback. We are currently looking at alternative content delivery methods in 2020 that may provide additional ways to test code. I'm also adding this lesson to a list of general React issues to help us set up future curriculum work.

Since this is a suggestion and not an issue specifically with this lesson, I am going to close it for now, but will follow up here when we've resolved this request.
